### PR TITLE
Switched to AsyncKeyedLock library

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@donaldgray this library will bring better performance and lower memory usage.

**Comment by MarkCiliaVincenti** [comment]
@donaldgray

**Comment by donaldgray** [comment]
Thanks @MarkCiliaVincenti - I saw your post about this on r/dotnet a few weeks ago and had been meaning to check it out!

**Comment by MarkCiliaVincenti** [comment]
> Thanks @MarkCiliaVincenti - I saw your post about this on r/dotnet a few weeks ago and had been meaning to check it out!

Cheers, I just updated the test that was broken :)

**Comment by MarkCiliaVincenti** [comment]
@donaldgray ?

**Comment by MarkCiliaVincenti** [comment]
@donaldgray any thoughts on this?

**Comment by donaldgray** [comment]
Hi @MarkCiliaVincenti, I had some extended downtime over the festive period so haven't had a chance to properly look at it yet. On initial scan of PR it looks fine though - I'll hopefully get some time to look soon.

**Comment by MarkCiliaVincenti** [comment]
@donaldgray gentle nudge :)

**Comment by donaldgray** [comment]
Hi @MarkCiliaVincenti, this PR is very much appreciated but unfortunately, due to timing, it might be a while before this is reviewed.

We discussed this it internally last week but we're in the middle of a package of work to finalise a new release of this application so all focus is on getting related tickets done.

**Comment by MarkCiliaVincenti** [comment]
OK, thanks for the heads up.

**Comment by MarkCiliaVincenti** [comment]
@donaldgray have you gotten around to reviewing this yet, or will it suffer the same fate as iif-builder? :)

**Comment by donaldgray** [comment]
@MarkCiliaVincenti - We appreciate you opening this PR but have decided to close the issue. The main usage that we have for `AsyncKeyedLock` is being superseded. 

We were using it to reorganise some objects stored in S3 on the fly as the layout for these have changed between an old version of this application and now. However, we've decided to bulk-reorganise these and will remove that branch from the codebase.

**Pull request closed without merging**
